name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Generate 3D Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jgj1020
          
      - name: Commit & Push Changes
        run: |
          git config --local user.name "jgj1020"
          git config --local user.email "s2433@e-mirim.hs.kr"
          git add -A .
          git commit -m "Generated 3D Profile Contrib" || exit 0
          git push
